# -*- coding: utf-8 -*-
"""conversational_LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhGYWbC_2Xam2LEQUmaZcXywPracd33D
"""

!pip install torch datasets transformers -q

import torch
import torch.nn as nn
import torch.nn.functional as F
from datasets import load_dataset
from tqdm import tqdm
import time

torch.manual_seed(1337)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

# STEP 1: DOWNLOAD CONVERSATIONAL DATA
# ============================================================================

print("\n" + "="*60)
print("DOWNLOADING OPENWEBTEXT DATASET")
print("="*60)
print("This contains Reddit posts, articles, and discussions")
print("Much better for general conversation!")
print()

# Download 1% of OpenWebText (~80MB of text)
dataset = load_dataset("Skylion007/openwebtext", split="train[:3%]")

# Extract text
all_texts = []
for item in tqdm(dataset, desc="Extracting text"):
    text = item['text']
    # Only keep texts longer than 100 characters
    if len(text) > 100:
        all_texts.append(text)

# Combine into one big text
text = '\n\n'.join(all_texts[:10000])  # Use first 10,000 articles

print(f"\n✓ Dataset loaded: {len(text):,} characters")
print(f"✓ Number of articles: {len(all_texts[:10000]):,}")

print("\nSample of the data:")
print("-" * 60)
print(text[:500])
print("-" * 60)

"""##CREATE TOKENIZER

"""

print("\n" + "="*60)
print("CREATING TOKENIZER")
print("="*60)

chars = sorted(list(set(text)))
vocab_size = len(chars)

char_to_idx = {ch: i for i, ch in enumerate(chars)}
idx_to_char = {i: ch for i, ch in enumerate(chars)}

encode = lambda s: [char_to_idx[c] for c in s if c in char_to_idx]
decode = lambda l: ''.join([idx_to_char[i] for i in l])

print(f"Vocabulary size: {vocab_size}")
print(f"Sample encoding: {encode('Hello world')[:20]}")

"""##PREPARE DATA"""

print("\n" + "="*60)
print("PREPARING TRAINING DATA")
print("="*60)

data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

print(f"Train tokens: {len(train_data):,}")
print(f"Val tokens: {len(val_data):,}")

# Hyperparameters
batch_size = 64
block_size = 512  # Context length

def get_batch(split):
    data_split = train_data if split == 'train' else val_data
    ix = torch.randint(len(data_split) - block_size, (batch_size,))
    x = torch.stack([data_split[i:i+block_size] for i in ix])
    y = torch.stack([data_split[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

"""##MODEL ARCHITECTURE"""

class MultiHeadAttention(nn.Module):
    """ Vectorized Multi-Head Attention """
    def __init__(self, n_embd, n_head, block_size, dropout=0.2):
        super().__init__()
        assert n_embd % n_head == 0
        self.n_head = n_head
        self.n_embd = n_embd

        # Key, query, value projections for all heads
        self.qkv_proj = nn.Linear(n_embd, 3 * n_embd, bias=False)
        # Output projection
        self.out_proj = nn.Linear(n_embd, n_embd)

        # Regularization
        self.attn_dropout = nn.Dropout(dropout)
        self.resid_dropout = nn.Dropout(dropout)

        # Causal mask
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size))
                                    .view(1, 1, block_size, block_size))

    def forward(self, x):
        B, T, C = x.shape # batch size, sequence length, embedding dimensionality (n_embd)

        # calculate query, key, values for all heads in batch
        qkv = self.qkv_proj(x)
        q, k, v = qkv.split(self.n_embd, dim=2)

        # reshape for multi-head attention
        k = k.view(B, T, self.n_head, C // self.n_head).transpose(1, 2) # (B, nh, T, hs)
        q = q.view(B, T, self.n_head, C // self.n_head).transpose(1, 2) # (B, nh, T, hs)
        v = v.view(B, T, self.n_head, C // self.n_head).transpose(1, 2) # (B, nh, T, hs)

        # causal self-attention
        # (B, nh, T, hs) x (B, nh, hs, T) -> (B, nh, T, T)
        wei = (q @ k.transpose(-2, -1)) * (k.shape[-1] ** -0.5)
        wei = wei.masked_fill(self.tril[:, :, :T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.attn_dropout(wei)

        # (B, nh, T, T) x (B, nh, T, hs) -> (B, nh, T, hs)
        out = wei @ v

        # concatenate all heads
        out = out.transpose(1, 2).contiguous().view(B, T, C)

        # output projection
        out = self.resid_dropout(self.out_proj(out))
        return out

class FeedForward(nn.Module):
    def __init__(self, n_embd, dropout=0.2):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.GELU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    def __init__(self, n_embd, n_head, block_size, dropout=0.2):
        super().__init__()
        self.sa = MultiHeadAttention(n_embd, n_head, block_size, dropout)
        self.ffwd = FeedForward(n_embd, dropout)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        # Pre-LN architecture
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class ConversationalLLM(nn.Module):
    def __init__(self, vocab_size, block_size, n_embd=256, n_head=4, n_layer=4, dropout=0.2):
        super().__init__()
        self.block_size = block_size
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head, block_size, dropout) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    @torch.no_grad()
    def generate(self, idx, max_new_tokens, temperature=1.0, top_k=None):
        self.eval()
        for _ in range(max_new_tokens):
            idx_cond = idx if idx.size(1) <= self.block_size else idx[:, -self.block_size:]
            logits, _ = self(idx_cond)
            logits = logits[:, -1, :] / temperature

            if top_k is not None:
                v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
                logits[logits < v[:, [-1]]] = -float('Inf')

            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)

        self.train()
        return idx

# Create model
model = ConversationalLLM(
    vocab_size=vocab_size,
    block_size=block_size,
    n_embd=384,
    n_head=6,
    n_layer=6,
    dropout=0.2
)
model = model.to(device)

n_params = sum(p.numel() for p in model.parameters())
print(f"\n✓ Model created: {n_params:,} parameters")

"""##TRAINING"""

print("\n" + "="*60)
print("STARTING TRAINING ON CONVERSATIONAL DATA")
print("="*60)

max_iters = 5000
eval_interval = 300
learning_rate = 3e-4
eval_iters = 20

optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
# Add learning rate scheduler
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max_iters)

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

train_losses = []
val_losses = []
start_time = time.time()

for iter in tqdm(range(max_iters), desc="Training"):

    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        train_losses.append(losses['train'])
        val_losses.append(losses['val'])

        elapsed = time.time() - start_time
        print(f"\n{'='*60}")
        print(f"Step {iter}/{max_iters} | Time: {elapsed/60:.1f} min")
        print(f"Train Loss: {losses['train']:.4f} | Val Loss: {losses['val']:.4f}")

        # Generate sample
        context = torch.zeros((1, 1), dtype=torch.long, device=device)
        generated = model.generate(context, max_new_tokens=200, temperature=0.8, top_k=40)
        print(f"\nGenerated sample:")
        print(decode(generated[0].tolist()))
        print("="*60)

    xb, yb = get_batch('train')
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    scheduler.step()

total_time = time.time() - start_time
print(f"\n✓ Training complete in {total_time/60:.1f} minutes!")

"""##GENERATE CONVERSATIONS"""

def generate_text(prompt="", max_tokens=300, temperature=0.8, top_k=40):
    if prompt:
        context = torch.tensor([encode(prompt)], dtype=torch.long, device=device)
    else:
        context = torch.zeros((1, 1), dtype=torch.long, device=device)

    generated = model.generate(context, max_new_tokens=max_tokens, temperature=temperature, top_k=top_k)
    return decode(generated[0].tolist())

print("\n" + "="*60)
print("GENERATION EXAMPLES - GENERAL CONVERSATION")
print("="*60)

# Example 1: General conversation
print("\n1. Prompt: 'Hello, how are you?'")
print("-" * 60)
print(generate_text(prompt="Hello, how are you?", max_tokens=200))

# Example 2: Question
print("\n" + "="*60)
print("2. Prompt: 'What is the meaning of'")
print("-" * 60)
print(generate_text(prompt="What is the meaning of", max_tokens=200))

# Example 3: Story
print("\n" + "="*60)
print("3. Prompt: 'Once upon a time'")
print("-" * 60)
print(generate_text(prompt="Once upon a time", max_tokens=250))

# Example 4: Technical
print("\n" + "="*60)
print("4. Prompt: 'The reason why'")
print("-" * 60)
print(generate_text(prompt="The reason why", max_tokens=200))

